[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.2
blur  = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 17

[terminal]

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["-l"]
